
(()=>{
'use strict';
const VERSION='14.2', KEY='roulettePatternLab.v14.2', THEME_KEY='roulettePatternLab.theme';
const FAMILIES=['sequence','jump','joint','pair','transition'];
const CACHE_LIMIT=80;
const $=id=>document.getElementById(id);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const wheel=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const pos=new Map(wheel.map((n,i)=>[n,i]));
const red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const cache={candidates:new Map(),familyTarget:new Map(),familyBacktest:new Map(),meta:new Map(),model:new Map(),memory:new Map(),trans:new Map()};
const emptyPerf=()=>({n:0,hit:0,exact:0,edge:0,recentEdge:0,robustEdge:0,stability:0,stability20:0,windowEdge:0});
let S=loadState();
function fresh(){return {version:VERSION,spins:[],predictions:[],settings:{tol:3,chartWindow:60}}}
function normalize(x){
  const s=fresh();
  if(!x||typeof x!=='object')return s;
  s.spins=Array.isArray(x.spins)?x.spins.map((v,i)=>({id:Number(v.id)||i+1,result:Number(v.result),createdAt:v.createdAt||new Date().toISOString()})).filter(v=>Number.isInteger(v.result)&&v.result>=0&&v.result<=36):[];
  s.settings={tol:clamp(Number(x.settings?.tol)||3,1,9),chartWindow:[30,60,120].includes(Number(x.settings?.chartWindow))?Number(x.settings.chartWindow):60};
  s.predictions=Array.isArray(x.predictions)?x.predictions:[];
  s.version=VERSION;
  return s;
}
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x?.spins)return normalize(x)}catch{} for(const k of ['roulettePatternLab.v13.6','roulettePatternLab.v13.5','roulettePatternLab.v13.4','roulettePatternLab.v12','roulettePatternLab.v10']){try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x?.spins){const s=normalize(x);localStorage.setItem(KEY,JSON.stringify(s));return s}}catch{}} return fresh()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}}
function invalidateAll(){Object.values(cache).forEach(m=>m.clear())}
function hashHistory(h,tol){let x=2166136261;for(let i=0;i<h.length;i++){x^=h[i]+i*31;x=Math.imul(x,16777619)}return (x>>>0)+'|'+tol+'|'+h.length+(h.length?h[h.length-1]:'')}
function keyArr(a){return a.join(',')}
function idx(n){return pos.get(n) ?? 0}
function col(n){return n===0?'green':red.has(n)?'red':'black'}
function jmp(a,b){if(a==null||b==null)return 0;let d=idx(b)-idx(a);if(d>18)d-=37;if(d<-18)d+=37;return d}
function dist(a,b){return Math.min(Math.abs(idx(a)-idx(b)),37-Math.abs(idx(a)-idx(b)))}
function dir(a,b){const j=jmp(a,b);return j>0?'CW':j<0?'CCW':'SAME'}
function neigh(n,t){return Array.from({length:2*t+1},(_,k)=>wheel[(idx(n)-t+k+37*4)%37])}
function baseline(t){return (2*t+1)/37}
function pct(a,b){return b?(100*a/b).toFixed(1)+'%':'—'}
function robustEdgeWilson(hit,n,tol){
  if(!n)return 0;
  const z=1.96,p=hit/n,den=1+z*z/n,center=(p+z*z/(2*n))/den,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;
  return center-half-baseline(tol);
}
function getTrans(h){const k=keyArr(h);if(cache.trans.has(k))return cache.trans.get(k);const a=[];for(let i=1;i<h.length;i++)a.push({from:h[i-1],to:h[i],j:jmp(h[i-1],h[i]),d:dir(h[i-1],h[i])});cache.trans.set(k,a);return a}
function candidates(h,f,minOcc=2){
  const key=hashHistory(h,0)+'|'+f+'|'+minOcc;if(cache.candidates.has(key))return cache.candidates.get(key);
  if(h.length<12){cache.candidates.set(key,[]);return []}
  const out=[];
  if(f==='sequence'){
    for(let l=2;l<=Math.min(8,h.length-1);l++){const sig=h.slice(-l).join(',');const next=[];for(let i=0;i+l<h.length;i++){if(h.slice(i,i+l).join(',')===sig)next.push(h[i+l])}if(next.length>=minOcc)out.push({type:f,len:l,key:sig,occ:next.length,next})}
  }else if(f==='jump'){
    const a=getTrans(h).map(x=>x.j);for(let l=2;l<=Math.min(6,a.length-1);l++){const sig=a.slice(-l).join(',');const next=[];for(let i=0;i+l<a.length;i++){if(a.slice(i,i+l).join(',')===sig)next.push(a[i+l])}if(next.length>=minOcc)out.push({type:f,len:l,key:sig,occ:next.length,next})}
  }else if(f==='joint'){
    const a=getTrans(h).map(x=>x.j+':'+x.d);for(let l=2;l<=Math.min(6,a.length-1);l++){const sig=a.slice(-l).join('|');const next=[];for(let i=0;i+l<a.length;i++){if(a.slice(i,i+l).join('|')===sig)next.push(h[i+l])}if(next.length>=minOcc)out.push({type:f,len:l,key:sig,occ:next.length,next})}
  }else if(f==='pair'){
    const sig=h.slice(-2).join(','),next=[];for(let i=0;i+2<h.length;i++)if(h[i]+','+h[i+1]===sig)next.push(h[i+2]);if(next.length>=minOcc)out.push({type:f,len:2,key:sig,occ:next.length,next});
  }else{
    const sig=String(h.at(-1)),next=[];for(let i=0;i<h.length-1;i++)if(h[i]===h.at(-1))next.push(h[i+1]);if(next.length>=minOcc)out.push({type:f,len:1,key:sig,occ:next.length,next});
  }
  const r=out.sort((a,b)=>b.len-a.len||b.occ-a.occ);cache.candidates.set(key,r);return r;
}
function weightedFamilyTarget(h,f,minOcc=2){
  const key=hashHistory(h,0)+'|'+f+'|'+minOcc;if(cache.familyTarget.has(key))return cache.familyTarget.get(key);
  const cs=candidates(h,f,minOcc);if(!cs.length){cache.familyTarget.set(key,null);return null}
  const q=Array(37).fill(0);
  cs.slice(0,5).forEach(p=>{const reliability=clamp(0.58+0.05*Math.min(p.occ,10)+0.045*Math.min(p.len,8),0.58,1.25);const uniq=new Set(p.next);uniq.forEach(n=>q[idx(n)]+=reliability/Math.max(1,uniq.size))});
  let best=0;for(let n=1;n<37;n++)if(q[n]>q[best])best=n;const ans=q[best]?best:null;cache.familyTarget.set(key,ans);return ans;
}
function learningTarget(h,f){
  // Walk-forward learning may use a shorter pattern when the longest/current
  // pattern has no historical repetition. This affects learning evaluation
  // only; prediction candidates keep their existing evidence requirements.
  const max=f==='pair'?2:(f==='transition'?1:(f==='sequence'?8:6));
  const min=f==='pair'?2:1;
  for(let l=max;l>=min;l--){
    const t=weightedFamilyTarget(h,f,l);
    if(t!=null)return t;
  }
  return null;
}
function familyBacktest(h,f,tol){
  const key=hashHistory(h,tol)+'|'+f;if(cache.familyBacktest.has(key))return cache.familyBacktest.get(key);
  if(h.length<14){const z=emptyPerf();cache.familyBacktest.set(key,z);return z}
  const start=Math.max(12,h.length-160),rows=[];
  for(let i=start;i<h.length;i++){const t=learningTarget(h.slice(0,i),f);if(t==null)continue;rows.push({hit:dist(t,h[i])<=tol,exact:dist(t,h[i])===0})}
  if(!rows.length){const z=emptyPerf();cache.familyBacktest.set(key,z);return z}
  const n=rows.length,hit=rows.filter(x=>x.hit).length,exact=rows.filter(x=>x.exact).length,recent=rows.slice(-Math.min(20,n)),rh=recent.filter(x=>x.hit).length;
  const edge=hit/n-baseline(tol),recentEdge=rh/recent.length-baseline(tol),robust=robustEdgeWilson(hit,n,tol),mid=Math.max(10,Math.floor(n/2)),a=rows.slice(0,mid),b=rows.slice(mid),ra=a.length?a.filter(x=>x.hit).length/a.length:0,rb=b.length?b.filter(x=>x.hit).length/b.length:0;
  const stability20=clamp(1-Math.abs(edge-recentEdge)/Math.max(0.05,Math.abs(edge)+0.02),0,1),stabilityHalf=clamp(1-Math.abs(ra-rb)/Math.max(0.10,Math.abs(ra)+Math.abs(rb)+0.10),0,1);
  const result={n,hit,exact,edge,recentEdge,robustEdge:robust,stability:0.55*stability20+0.45*stabilityHalf,stability20,windowEdge:edge};cache.familyBacktest.set(key,result);return result;
}
function metaBacktest(h,tol){
  const key=hashHistory(h,tol)+'|meta';if(cache.meta.has(key))return cache.meta.get(key);const combos={};
  for(let i=Math.max(14,h.length-140);i<h.length;i++){
    const hh=h.slice(0,i),targets={};FAMILIES.forEach(f=>targets[f]=weightedFamilyTarget(hh,f));const active=FAMILIES.filter(f=>targets[f]!=null);
    for(let a=0;a<active.length;a++)for(let b=a+1;b<active.length;b++){const fa=active[a],fb=active[b],same=targets[fa]===targets[fb];if(!same)continue;const k=fa+'+'+fb;(combos[k]??={n:0,hit:0}).n++;if(dist(targets[fa],h[i])<=tol)combos[k].hit++}
  }
  const out={};Object.entries(combos).forEach(([k,v])=>out[k]={...v,edge:v.hit/v.n-baseline(tol),robustEdge:robustEdgeWilson(v.hit,v.n,tol)});cache.meta.set(key,out);return out;
}
function adaptive(h,tol){
  const perf={},weights={};FAMILIES.forEach(f=>{const p=familyBacktest(h,f,tol);perf[f]=p;const sample=clamp(p.n/70,0,1),robustBoost=clamp(1+p.robustEdge*7,0.45,1.65),recency=clamp(1+p.recentEdge*4,0.65,1.35),stability=0.78+0.22*p.stability;weights[f]=clamp(0.55+0.90*sample*robustBoost*recency*stability,0.45,2.0)});return {perf,weights,meta:metaBacktest(h,tol)};
}
function calibrateRelative(scores){
  const floor=0.015,temps=scores.map(v=>Math.sqrt(Math.max(v,0)));const sum=temps.reduce((a,b)=>a+b,0)||1;return temps.map(v=>Math.max(floor,v/sum));
}
function model(h,tol){
  const key=hashHistory(h,tol);if(cache.model.has(key))return cache.model.get(key);if(h.length<12)return null;
  const a=adaptive(h,tol),score=Array(37).fill(0.018),support=Array(37).fill(0),familyTargets={};
  for(const f of FAMILIES){const w=a.weights[f],cs=candidates(h,f),ft=weightedFamilyTarget(h,f);familyTargets[f]=ft;cs.slice(0,5).forEach(q=>{const lenBoost=q.len>=6?1.25:q.len>=4?1.12:1,occBoost=clamp(Math.log2(q.occ+1)/2,0.5,1.35),sampleConfidence=clamp(q.occ/7,0.35,1),localW=w*lenBoost*occBoost*sampleConfidence,uniq=[...new Set(q.next)];uniq.forEach(n=>{score[idx(n)]+=localW/Math.max(1,uniq.length);support[idx(n)]++})})}
  Object.entries(a.meta).forEach(([k,m])=>{if(m.n<6||m.robustEdge<=0)return;const [fa,fb]=k.split('+'),t=familyTargets[fa];if(t!=null&&familyTargets[fb]===t){score[idx(t)]+=clamp(m.robustEdge*16,0.03,0.55);support[idx(t)]+=0.5}});
  const last=h.at(-1),row=Array(37).fill(0);for(let i=0;i<h.length-1;i++)if(h[i]===last)row[idx(h[i+1])]++;const rz=row.reduce((a,b)=>a+b,0);if(rz)for(let n=0;n<37;n++)if(row[n])score[n]+=0.95*(row[n]/rz);
  const recent=h.slice(-10),cnt=new Map();recent.forEach(n=>cnt.set(n,(cnt.get(n)||0)+1));for(let n=0;n<37;n++){const c=cnt.get(n)||0;if(c>=3)score[n]*=(c===3?0.90:c===4?0.82:0.72)}
  const probs=calibrateRelative(score),ranked=score.map((v,n)=>({n,v,p:probs[n],support:support[n],transition:row[n]})).sort((a,b)=>b.p-a.p||b.support-a.support||b.transition-a.transition),top=ranked[0],second=ranked[1],lead=top.p-second.p;
  let cw=0,ccw=0;for(const x of ranked){const j=jmp(last,x.n);if(j>0)cw+=x.p;else if(j<0)ccw+=x.p}const active=FAMILIES.filter(f=>a.perf[f].n>0).length;
  const familyRobust=FAMILIES.map(f=>a.perf[f].n?a.perf[f].robustEdge:0).filter(x=>Number.isFinite(x)),avgRobust=familyRobust.length?familyRobust.reduce((s,x)=>s+x,0)/familyRobust.length:0;
  const familyRecent=FAMILIES.map(f=>a.perf[f].n?a.perf[f].recentEdge:0).filter(x=>Number.isFinite(x)),avgRecent=familyRecent.length?familyRecent.reduce((s,x)=>s+x,0)/familyRecent.length:0;
  const edge=top.p-baseline(tol),robustEdge=avgRobust,consensusCount=FAMILIES.filter(f=>a.perf[f].n&&familyTargets[f]===top.n).length,consensus=active?consensusCount/active:0;
  const stability=clamp(0.55*clamp(1-Math.abs(avgRobust-avgRecent)/Math.max(0.05,Math.abs(avgRobust)+0.02),0,1)+0.45*(FAMILIES.reduce((s,f)=>s+(a.perf[f].n?a.perf[f].stability:0),0)/Math.max(1,active)),0,1);
  const recentQuality=clamp((avgRecent+baseline(tol))/(Math.max(0.001,1-baseline(tol))),0,1),sampleQuality=clamp((a.perf[topSupportFamily(ranked, a, familyTargets, top.n)]?.n||0)/100,0,1);
  const confidence=Math.round(clamp(28+lead*1000+clamp(top.support/Math.max(1,active),0,1)*22+consensus*25+stability*12+clamp(avgRobust*400,-8,20),5,99));
  const quality=Math.round(clamp(consensus*28+stability*22+clamp((robustEdge+0.03)/0.08,0,1)*25+clamp((Math.log1p(Math.max(0,top.support))/3),0,1)*10+recentQuality*15,0,100));
  const signal=!ranked.length||active<2||confidence<45||edge<0.003||robustEdge<=0?'NONE':confidence>=72&&robustEdge>=0.008&&quality>=70?'HIGH':'LOW';
  const target=ranked.length?top.n:null,jump=target==null?null:jmp(last,target);
  const result={target,prob:target==null?0:top.p,ranking:ranked.slice(0,12),predDir:cw>=ccw?'CW':'CCW',cw,ccw,adaptive:a,seq:candidates(h,'sequence').slice(0,4),joint:candidates(h,'joint').slice(0,3),jumps:candidates(h,'jump').slice(0,3),edge,robustEdge,confidence,signal,lead,avgEdge:avgRobust,avgRecent,stability,consensusCount,activeModels:active,jump,quality,familyTargets};
  cache.model.set(key,result);if(cache.model.size>CACHE_LIMIT)cache.model.delete(cache.model.keys().next().value);return result;
}
function topSupportFamily(ranked,a,targets,n){let best=FAMILIES[0],bn=-1;for(const f of FAMILIES){const q=a.perf[f];if(targets[f]===n&&(q.n>bn)){best=f;bn=q.n}}return best}
function rebuildPredictions(){
  const h=S.spins.map(x=>x.result),out=[];for(let i=0;i<h.length;i++){const prior=h.slice(0,i);if(prior.length<12)continue;const p=model(prior,S.settings.tol);if(p)out.push({id:out.length+1,spinIndex:i+1,previous:prior.at(-1)??null,prediction:p,actual:h[i],createdAt:S.spins[i].createdAt||new Date().toISOString()})}S.predictions=out;
}
function ensurePredictions(){
  const expected=Math.max(0,S.spins.length-12),last=S.predictions.at(-1)?.spinIndex||0,valid=S.predictions.length===expected&&last===S.spins.length&&S.predictions.every(x=>Number.isFinite(x?.prediction?.prob)&&x?.prediction?.target!=null);if(!valid){rebuildPredictions();save()}
}
function backtest(tol){ensurePredictions();const rows=S.predictions.filter(x=>x?.prediction?.target!=null&&x.spinIndex<=S.spins.length),n=rows.length,hit=rows.filter(x=>dist(x.prediction.target,x.actual)<=tol).length,exact=rows.filter(x=>dist(x.prediction.target,x.actual)===0).length,dirHit=rows.filter(x=>x.prediction.predDir&&x.previous!=null&&x.prediction.predDir===dir(x.previous,x.actual)).length;return {n,hit,exact,dir:dirHit,rows}}
function patternMemory(h){const key=hashHistory(h,0);if(cache.memory.has(key))return cache.memory.get(key);const mem={};FAMILIES.forEach(f=>candidates(h,f).forEach(q=>{const k=q.type+'|'+q.key;if(!mem[k])mem[k]={type:q.type,key:q.key,occ:q.occ,next:{}};mem[k].occ=Math.max(mem[k].occ,q.occ);q.next.forEach(n=>mem[k].next[n]=(mem[k].next[n]||0)+1)}));const out=Object.values(mem);cache.memory.set(key,out);return out}
function add(n){
  const value=Number(n),h=S.spins.map(x=>x.result),now=new Date().toISOString();
  const p=h.length>=12?model(h,S.settings.tol):null;
  S.spins.push({id:S.spins.length?Math.max(...S.spins.map(x=>x.id))+1:1,result:value,createdAt:now});
  if(p)S.predictions.push({id:S.predictions.length?Math.max(...S.predictions.map(x=>x.id))+1:1,spinIndex:S.spins.length,previous:h.at(-1)??null,prediction:p,actual:value,createdAt:now});
  invalidateAll();save();render();
}
function undo(){if(!S.spins.length)return;S.spins.pop();S.predictions=(S.predictions||[]).filter(x=>x.spinIndex<=S.spins.length);invalidateAll();save();render()}
function clearAll(){if(confirm('¿Borrar todo el histórico?')){S=fresh();invalidateAll();save();render()}}
function render(){
  const h=S.spins.map(x=>x.result),t=getTrans(h),p=model(h,S.settings.tol),bt=backtest(S.settings.tol),tol=S.settings.tol;
  document.querySelectorAll('.tolText').forEach(e=>e.textContent=tol);$('counter').textContent=h.length+' spins';$('evals').textContent=bt.n;$('tolLabel').textContent=tol;
  $('history').innerHTML=h.slice(-80).reverse().map(n=>`<span class="result ${col(n)}">${n}</span>`).join('')||`<span class="muted">${t('noResults')}</span>`;
  $('jumps').innerHTML=t.slice(-80).reverse().map(x=>`<span class="chip">${x.j>=0?'+':''}${x.j}</span>`).join('')||'<span class="muted">—</span>';
  $('dirs').innerHTML=t.slice(-80).reverse().map(x=>`<span class="chip">${x.d}</span>`).join('')||'<span class="muted">—</span>';
  $('tol').value=String(tol);
  if(!p){renderEmpty(h);drawChart();return}
  const tg=$('target');tg.textContent=p.target==null?'—':p.target;tg.className='target '+(p.target==null?'black':col(p.target));$('prob').textContent=p.target==null?'—':(p.prob*100).toFixed(2)+'%';
  
  $('predDir').textContent=p.target==null?'—':`${LANGS[LANG].direction|| (LANG==='es'?'Dirección':'Direction')}: ${p.predDir} · CW ${(p.cw*100).toFixed(1)}% / CCW ${(p.ccw*100).toFixed(1)}%`;$('predJump').textContent=p.target==null?'—':`${LANGS[LANG].predictedJump}: ${p.jump>=0?'+':''}${p.jump} pockets`;$('zone').textContent=p.target==null?'No hay zona con evidencia suficiente':neigh(p.target,tol).join(' · ');
  $('confidence').textContent=p.confidence+'/100';$('edge').textContent=fmtPP(p.edge);$('support').textContent=p.activeModels+'/'+FAMILIES.length;$('qualityMini').textContent=p.quality+'/100';$('quality').textContent=p.quality;$('qualityFill').style.width=p.quality+'%';$('qualitySummary').textContent=`La calidad combina consenso, estabilidad, edge robusto, tamaño de muestra y comportamiento reciente. No equivale a una probabilidad garantizada de acierto.`;
  $('qConsensus').textContent=Math.round((p.activeModels?p.consensusCount/p.activeModels:0)*100)+'/100';$('qStability').textContent=Math.round(p.stability*100)+'/100';$('qRobust').textContent=fmtPP(p.robustEdge);$('qSample').textContent=Math.round(clamp((p.adaptive.perf[topSupportFamily(p.ranking,p.adaptive,p.familyTargets,p.target)]?.n||0)/100,0,1)*100)+'/100';$('qRecent').textContent=Math.round(clamp((p.avgRecent+baseline(tol))/(Math.max(0.001,1-baseline(tol))),0,1)*100)+'/100';
  $('robustEdge').textContent=fmtPP(p.robustEdge);$('consensus').textContent=p.consensusCount+'/'+p.activeModels;$('stability').textContent=Math.round(p.stability*100)+'/100';
  $('ranking').innerHTML=p.ranking.slice(0,3).map((x,i)=>`<div class="rank"><div class="ranktop"><span>#${i+1} · ${x.n}${x.support?` · ${x.support} apoyos`:''}</span><b>${(x.p*100).toFixed(2)}%</b></div><div class="bar"><i style="width:${Math.max(2,100*x.p/p.ranking[0].p)}%"></i></div></div>`).join('');
  $('alerts').innerHTML=[...p.seq,...p.joint,...p.jumps].slice(0,7).map(q=>`<div class="alert"><b>${q.type==='sequence'?'SECUENCIA':q.type==='joint'?'SALTO + DIRECCIÓN':'PATRÓN DE SALTOS'}</b><br>${esc(q.key).replaceAll(',',' → ')} · ${q.occ} coincidencias · siguientes: ${q.next.join(', ')}</div>`).join('')||`<span class="muted">${t('noPattern')}</span>`;
  $('weights').innerHTML=FAMILIES.map(k=>{const v=p.adaptive.weights[k],q=p.adaptive.perf[k];return `<div class="weight"><span class="muted">${k}</span><br><b>${v.toFixed(2)}×</b><div class="muted">${q.n} tests · ±${tol}: ${pct(q.hit,q.n)} · edge ${q.n?fmtPP(q.edge):'—'} · reciente ${q.n?fmtPP(q.recentEdge):'—'} · robusto ${q.n?fmtPP(q.robustEdge):'—'}</div></div>`}).join('');
  $('weightSummary').textContent='Los pesos se calculan únicamente con resultados disponibles antes de cada evaluación. Las predicciones históricas no se recalculan al añadir spins nuevos.';
  $('learningSummary').textContent=FAMILIES.map(f=>{const q=p.adaptive.perf[f];return q.n?`${f}: ${q.n} tests, ${fmtPP(q.edge)} histórico, ${fmtPP(q.recentEdge)} reciente, ${Math.round(q.stability*100)}/100 estabilidad`:`${f}: sin muestra`}).join(' · ');
  $('predHistory').innerHTML=bt.rows.slice(-60).reverse().map(x=>{const pr=x.prediction,win=dist(pr.target,x.actual)<=tol,j=pr.jump==null?'—':`${pr.jump>=0?'+':''}${pr.jump}`;return `<div class="prow"><b>#${x.spinIndex}</b><span>${pr.target} → ${x.actual}</span><span>${j} pockets</span><span>${(pr.prob*100).toFixed(2)}%</span><span>${pr.confidence}/100</span><b class="${win?'win':'loss'}">${win?'WIN':'LOSS'}</b></div>`}).join('')||'—';
  const base=100*baseline(tol), recentRows=bt.rows.slice(-20),recentRate=recentRows.length?100*recentRows.filter(x=>dist(x.prediction.target,x.actual)<=tol).length/recentRows.length:null,chartRows=bt.rows.slice(-Number(S.settings.chartWindow)),chartRate=chartRows.length?100*chartRows.filter(x=>dist(x.prediction.target,x.actual)<=tol).length/chartRows.length:null;
  $('chartRate').textContent=chartRate==null?'—':chartRate.toFixed(1)+'%';$('chartBase').textContent=base.toFixed(1)+'%';$('chartEdge').textContent=chartRate==null?'—':((chartRate-base>=0?'+':'')+(chartRate-base).toFixed(1)+' pp');$('chartEval').textContent=chartRows.length;$('chartRecent').textContent=recentRate==null?'—':recentRate.toFixed(1)+'%';
  drawChart();
}
function renderEmpty(h){$('target').textContent='—';$('target').className='target black';$('prob').textContent='—';$('predDir').textContent=`${LANGS[LANG].direction}: —`;$('predJump').textContent=`${LANGS[LANG].predictedJump}: —`;$('zone').textContent=h.length<12?t('waitingData'):'—';$('confidence').textContent='—';$('edge').textContent='—';$('support').textContent='—';$('qualityMini').textContent='—';$('robustEdge').textContent='—';$('consensus').textContent='—';$('stability').textContent='—';$('quality').textContent='—';$('qualityFill').style.width='0%';$('qualitySummary').textContent='';['qConsensus','qStability','qRobust','qSample','qRecent'].forEach(id=>$(id).textContent='—');$('ranking').innerHTML='';$('alerts').innerHTML=h.length<12?t('waitingData')+'.':'—';$('weights').innerHTML=FAMILIES.map(k=>`<div class="weight"><span class="muted">${k}</span><br><b>—</b><div class="muted">Sin muestra</div></div>`).join('');$('learningSummary').textContent='';$('predHistory').innerHTML='—';}
function drawChart(){
  const c=$('chart'),d=devicePixelRatio||1,w=c.clientWidth||500,hh=c.clientHeight||240;c.width=w*d;c.height=hh*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,hh);const rows=S.predictions.filter(r=>r?.prediction?.target!=null),tol=S.settings.tol,win=Number(S.settings.chartWindow),slice=rows.slice(-win);if(!slice.length){x.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');x.font='12px system-ui';x.fillText('Aún no hay suficientes predicciones evaluadas.',12,25);return}
  const vals=[];let hits=0;const base=100*baseline(tol);slice.forEach(r=>{if(dist(r.prediction.target,r.actual)<=tol)hits++;vals.push(100*hits/(vals.length+1))});const color=getComputedStyle(document.body).getPropertyValue('--accent');x.strokeStyle=color;x.lineWidth=2;x.beginPath();vals.forEach((y,i,a)=>{const xx=8+i*(w-16)/Math.max(1,a.length-1),yy=hh-16-y*(hh-30)/100;i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();x.strokeStyle=getComputedStyle(document.body).getPropertyValue('--muted');x.lineWidth=1;x.setLineDash([4,4]);const by=hh-16-base*(hh-30)/100;x.beginPath();x.moveTo(8,by);x.lineTo(w-8,by);x.stroke();x.setLineDash([]);
}
function fmtPP(v){return (v*100>=0?'+':'')+(v*100).toFixed(1)+' pp'}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const LANG_KEY='roulettePatternLab.lang';
const LANGS={
  es:{name:'Español',brand:'Adaptive Pattern Engine',darkMode:'Modo noche',dayMode:'Modo día',undo:'Deshacer',clearHistory:'Borrar historial',resultInput:'Entrada de resultados',realtimePrediction:'Predicción en tiempo real',ensembleScore:'score relativo del ensemble',zoneLabel:'Zona ±',confidence:'Confianza',edgeLabel:'Edge ±',activeModels:'Modelos activos',quality:'Calidad',alternativePredictions:'Predicciones alternativas',top3:'Top 3',recentResults:'Últimos resultados',recentJumps:'Saltos recientes',recentDirections:'Direcciones recientes',predictionQuality:'Calidad de predicción',internalCalibration:'calibración interna',consensus:'Consenso',stability:'Estabilidad',robustEdge:'Edge robusto',sample:'Muestra',recency:'Recencia',learningDiagnosis:'Diagnóstico del aprendizaje',walkForward:'walk-forward',evaluated:'Evaluadas',adaptiveWeights:'Pesos adaptativos',walkForwardLearning:'aprendizaje walk-forward',activePatterns:'Patrones activos',predictionHistory:'Historial de predicciones',performanceTolerance:'Rendimiento ± tolerancia',window:'Ventana',winRate:'Win rate',baseline:'Baseline',edge:'Edge',last20:'Últimas 20',help:'Ayuda',close:'Cerrar',noResults:'Sin resultados',noPattern:'No hay patrón repetido suficiente.',waitingData:'Se necesitan al menos 12 spins.',noEvidence:'No hay zona con evidencia suficiente'},
  en:{name:'English',brand:'Adaptive Pattern Engine',darkMode:'Dark mode',dayMode:'Day mode',undo:'Undo',clearHistory:'Clear history',resultInput:'Result input',realtimePrediction:'Real-time prediction',ensembleScore:'relative ensemble score',zoneLabel:'Zone ±',confidence:'Confidence',edgeLabel:'Edge ±',activeModels:'Active models',quality:'Quality',alternativePredictions:'Alternative predictions',top3:'Top 3',recentResults:'Recent results',recentJumps:'Recent jumps',recentDirections:'Recent directions',predictionQuality:'Prediction quality',internalCalibration:'internal calibration',consensus:'Consensus',stability:'Stability',robustEdge:'Robust edge',sample:'Sample',recency:'Recency',learningDiagnosis:'Learning diagnostics',walkForward:'walk-forward',evaluated:'Evaluated',adaptiveWeights:'Adaptive weights',walkForwardLearning:'walk-forward learning',activePatterns:'Active patterns',predictionHistory:'Prediction history',performanceTolerance:'Performance ± tolerance',window:'Window',winRate:'Win rate',baseline:'Baseline',edge:'Edge',last20:'Last 20',help:'Help',close:'Close',noResults:'No results',noPattern:'Not enough repeated pattern evidence.',waitingData:'At least 12 spins are needed.',noEvidence:'No zone with sufficient evidence'},
  de:{name:'Deutsch',brand:'Adaptive Pattern Engine',darkMode:'Nachtmodus',dayMode:'Tagesmodus',undo:'Rückgängig',clearHistory:'Verlauf löschen',resultInput:'Ergebniseingabe',realtimePrediction:'Echtzeit-Prognose',ensembleScore:'relativer Ensemble-Score',zoneLabel:'Zone ±',confidence:'Konfidenz',edgeLabel:'Edge ±',activeModels:'Aktive Modelle',quality:'Qualität',alternativePredictions:'Alternative Prognosen',top3:'Top 3',recentResults:'Letzte Ergebnisse',recentJumps:'Letzte Sprünge',recentDirections:'Letzte Richtungen',predictionQuality:'Prognosequalität',internalCalibration:'interne Kalibrierung',consensus:'Konsens',stability:'Stabilität',robustEdge:'Robuster Edge',sample:'Stichprobe',recency:'Aktualität',learningDiagnosis:'Lerndiagnose',walkForward:'Walk-forward',evaluated:'Ausgewertet',adaptiveWeights:'Adaptive Gewichte',walkForwardLearning:'Walk-forward-Lernen',activePatterns:'Aktive Muster',predictionHistory:'Prognoseverlauf',performanceTolerance:'Leistung ± Toleranz',window:'Fenster',winRate:'Trefferquote',baseline:'Baseline',edge:'Edge',last20:'Letzte 20',help:'Hilfe',close:'Schließen',noResults:'Keine Ergebnisse',noPattern:'Nicht genügend wiederholte Musterbelege.',waitingData:'Mindestens 12 Spins werden benötigt.',noEvidence:'Keine Zone mit ausreichender Evidenz'},
  fr:{name:'Français',brand:'Adaptive Pattern Engine',darkMode:'Mode nuit',dayMode:'Mode jour',undo:'Annuler',clearHistory:"Effacer l’historique",resultInput:'Saisie des résultats',realtimePrediction:'Prédiction en temps réel',ensembleScore:'score relatif de l’ensemble',zoneLabel:'Zone ±',confidence:'Confiance',edgeLabel:'Edge ±',activeModels:'Modèles actifs',quality:'Qualité',alternativePredictions:'Prédictions alternatives',top3:'Top 3',recentResults:'Derniers résultats',recentJumps:'Sauts récents',recentDirections:'Directions récentes',predictionQuality:'Qualité des prédictions',internalCalibration:'calibration interne',consensus:'Consensus',stability:'Stabilité',robustEdge:'Edge robuste',sample:'Échantillon',recency:'Récence',learningDiagnosis:'Diagnostic de l’apprentissage',walkForward:'walk-forward',evaluated:'Évaluées',adaptiveWeights:'Poids adaptatifs',walkForwardLearning:'apprentissage walk-forward',activePatterns:'Motifs actifs',predictionHistory:'Historique des prédictions',performanceTolerance:'Performance ± tolérance',window:'Fenêtre',winRate:'Taux de réussite',baseline:'Référence',edge:'Edge',last20:'20 dernières',help:'Aide',close:'Fermer',noResults:'Aucun résultat',noPattern:'Pas assez de preuves de motifs répétés.',waitingData:'Au moins 12 tours sont nécessaires.',noEvidence:'Aucune zone avec suffisamment de preuves'},
  it:{name:'Italiano',brand:'Adaptive Pattern Engine',darkMode:'Modalità notte',dayMode:'Modalità giorno',undo:'Annulla',clearHistory:'Cancella cronologia',resultInput:'Inserimento risultati',realtimePrediction:'Predizione in tempo reale',ensembleScore:'punteggio relativo dell’ensemble',zoneLabel:'Zona ±',confidence:'Confidenza',edgeLabel:'Edge ±',activeModels:'Modelli attivi',quality:'Qualità',alternativePredictions:'Predizioni alternative',top3:'Top 3',recentResults:'Risultati recenti',recentJumps:'Salti recenti',recentDirections:'Direzioni recenti',predictionQuality:'Qualità della predizione',internalCalibration:'calibrazione interna',consensus:'Consenso',stability:'Stabilità',robustEdge:'Edge robusto',sample:'Campione',recency:'Recenza',learningDiagnosis:'Diagnostica dell’apprendimento',walkForward:'walk-forward',evaluated:'Valutate',adaptiveWeights:'Pesi adattivi',walkForwardLearning:'apprendimento walk-forward',activePatterns:'Pattern attivi',predictionHistory:'Cronologia delle predizioni',performanceTolerance:'Prestazioni ± tolleranza',window:'Finestra',winRate:'Percentuale di successo',baseline:'Baseline',edge:'Edge',last20:'Ultime 20',help:'Aiuto',close:'Chiudi',noResults:'Nessun risultato',noPattern:'Prove di pattern ripetuti insufficienti.',waitingData:'Sono necessari almeno 12 spin.',noEvidence:'Nessuna zona con prove sufficienti'},
  pt:{name:'Português',brand:'Adaptive Pattern Engine',darkMode:'Modo escuro',dayMode:'Modo claro',undo:'Desfazer',clearHistory:'Apagar histórico',resultInput:'Entrada de resultados',realtimePrediction:'Previsão em tempo real',ensembleScore:'pontuação relativa do ensemble',zoneLabel:'Zona ±',confidence:'Confiança',edgeLabel:'Edge ±',activeModels:'Modelos ativos',quality:'Qualidade',alternativePredictions:'Previsões alternativas',top3:'Top 3',recentResults:'Resultados recentes',recentJumps:'Saltos recentes',recentDirections:'Direções recentes',predictionQuality:'Qualidade da previsão',internalCalibration:'calibração interna',consensus:'Consenso',stability:'Estabilidade',robustEdge:'Edge robusto',sample:'Amostra',recency:'Recência',learningDiagnosis:'Diagnóstico da aprendizagem',walkForward:'walk-forward',evaluated:'Avaliadas',adaptiveWeights:'Pesos adaptativos',walkForwardLearning:'aprendizagem walk-forward',activePatterns:'Padrões ativos',predictionHistory:'Histórico de previsões',performanceTolerance:'Desempenho ± tolerância',window:'Janela',winRate:'Taxa de acerto',baseline:'Baseline',edge:'Edge',last20:'Últimas 20',help:'Ajuda',close:'Fechar',noResults:'Sem resultados',noPattern:'Evidência insuficiente de padrões repetidos.',waitingData:'São necessários pelo menos 12 spins.',noEvidence:'Nenhuma zona com evidência suficiente'},
  ru:{name:'Русский',brand:'Adaptive Pattern Engine',darkMode:'Ночной режим',dayMode:'Дневной режим',undo:'Отменить',clearHistory:'Очистить историю',resultInput:'Ввод результатов',realtimePrediction:'Прогноз в реальном времени',ensembleScore:'относительный балл ансамбля',zoneLabel:'Зона ±',confidence:'Уверенность',edgeLabel:'Edge ±',activeModels:'Активные модели',quality:'Качество',alternativePredictions:'Альтернативные прогнозы',top3:'Топ 3',recentResults:'Последние результаты',recentJumps:'Последние переходы',recentDirections:'Последние направления',predictionQuality:'Качество прогноза',internalCalibration:'внутренняя калибровка',consensus:'Консенсус',stability:'Стабильность',robustEdge:'Надёжный edge',sample:'Выборка',recency:'Актуальность',learningDiagnosis:'Диагностика обучения',walkForward:'walk-forward',evaluated:'Проверено',adaptiveWeights:'Адаптивные веса',walkForwardLearning:'обучение walk-forward',activePatterns:'Активные паттерны',predictionHistory:'История прогнозов',performanceTolerance:'Результативность ± допуск',window:'Окно',winRate:'Процент выигрышей',baseline:'Базовый уровень',edge:'Edge',last20:'Последние 20',help:'Помощь',close:'Закрыть',noResults:'Нет результатов',noPattern:'Недостаточно данных о повторяющихся паттернах.',waitingData:'Необходимо не менее 12 спинов.',noEvidence:'Нет зоны с достаточной доказательной базой'},
  ja:{name:'日本語',brand:'Adaptive Pattern Engine',darkMode:'ダークモード',dayMode:'ライトモード',undo:'元に戻す',clearHistory:'履歴を消去',resultInput:'結果入力',realtimePrediction:'リアルタイム予測',ensembleScore:'アンサンブル相対スコア',zoneLabel:'ゾーン ±',confidence:'信頼度',edgeLabel:'Edge ±',activeModels:'アクティブモデル',quality:'品質',alternativePredictions:'代替予測',top3:'Top 3',recentResults:'最近の結果',recentJumps:'最近のジャンプ',recentDirections:'最近の方向',predictionQuality:'予測品質',internalCalibration:'内部キャリブレーション',consensus:'合意',stability:'安定性',robustEdge:'ロバストEdge',sample:'サンプル',recency:'直近性',learningDiagnosis:'学習診断',walkForward:'walk-forward',evaluated:'評価数',adaptiveWeights:'適応重み',walkForwardLearning:'walk-forward学習',activePatterns:'アクティブパターン',predictionHistory:'予測履歴',performanceTolerance:'パフォーマンス ± 許容差',window:'ウィンドウ',winRate:'的中率',baseline:'ベースライン',edge:'Edge',last20:'直近20件',help:'ヘルプ',close:'閉じる',noResults:'結果なし',noPattern:'繰り返しパターンの証拠が不十分です。',waitingData:'最低12スピン必要です。',noEvidence:'十分な根拠のあるゾーンはありません'},
  zh:{name:'简体中文',brand:'Adaptive Pattern Engine',darkMode:'夜间模式',dayMode:'日间模式',undo:'撤销',clearHistory:'清除历史',resultInput:'结果输入',realtimePrediction:'实时预测',ensembleScore:'集成相对评分',zoneLabel:'区域 ±',confidence:'置信度',edgeLabel:'Edge ±',activeModels:'活跃模型',quality:'质量',alternativePredictions:'备选预测',top3:'Top 3',recentResults:'最近结果',recentJumps:'最近跳跃',recentDirections:'最近方向',predictionQuality:'预测质量',internalCalibration:'内部校准',consensus:'共识',stability:'稳定性',robustEdge:'稳健Edge',sample:'样本',recency:'近期性',learningDiagnosis:'学习诊断',walkForward:'walk-forward',evaluated:'已评估',adaptiveWeights:'自适应权重',walkForwardLearning:'walk-forward学习',activePatterns:'活跃模式',predictionHistory:'预测历史',performanceTolerance:'表现 ± 容差',window:'窗口',winRate:'命中率',baseline:'基线',edge:'Edge',last20:'最近20次',help:'帮助',close:'关闭',noResults:'暂无结果',noPattern:'重复模式证据不足。',waitingData:'至少需要12次旋转结果。',noEvidence:'没有证据足够的区域'},
  ko:{name:'한국어',brand:'Adaptive Pattern Engine',darkMode:'야간 모드',dayMode:'주간 모드',undo:'실행 취소',clearHistory:'기록 삭제',resultInput:'결과 입력',realtimePrediction:'실시간 예측',ensembleScore:'앙상블 상대 점수',zoneLabel:'구역 ±',confidence:'신뢰도',edgeLabel:'Edge ±',activeModels:'활성 모델',quality:'품질',alternativePredictions:'대체 예측',top3:'Top 3',recentResults:'최근 결과',recentJumps:'최근 점프',recentDirections:'최근 방향',predictionQuality:'예측 품질',internalCalibration:'내부 보정',consensus:'합의',stability:'안정성',robustEdge:'강건한 Edge',sample:'표본',recency:'최근성',learningDiagnosis:'학습 진단',walkForward:'walk-forward',evaluated:'평가 수',adaptiveWeights:'적응형 가중치',walkForwardLearning:'walk-forward 학습',activePatterns:'활성 패턴',predictionHistory:'예측 기록',performanceTolerance:'성능 ± 허용오차',window:'창',winRate:'적중률',baseline:'기준선',edge:'Edge',last20:'최근 20개',help:'도움말',close:'닫기',noResults:'결과 없음',noPattern:'반복 패턴의 근거가 충분하지 않습니다.',waitingData:'최소 12회 결과가 필요합니다.',noEvidence:'충분한 근거가 있는 구역이 없습니다'}
};
let LANG='es';
Object.assign(LANGS.es,{direction:'Dirección',predictedJump:'Salto previsto'});Object.assign(LANGS.en,{direction:'Direction',predictedJump:'Predicted jump'});Object.assign(LANGS.de,{direction:'Richtung',predictedJump:'Prognostizierter Sprung'});Object.assign(LANGS.fr,{direction:'Direction',predictedJump:'Saut prévu'});Object.assign(LANGS.it,{direction:'Direzione',predictedJump:'Salto previsto'});Object.assign(LANGS.pt,{direction:'Direção',predictedJump:'Salto previsto'});Object.assign(LANGS.ru,{direction:'Направление',predictedJump:'Прогнозируемый переход'});Object.assign(LANGS.ja,{direction:'方向',predictedJump:'予測ジャンプ'});Object.assign(LANGS.zh,{direction:'方向',predictedJump:'预测跳跃'});Object.assign(LANGS.ko,{direction:'방향',predictedJump:'예상 점프'});
function t(k){return LANGS[LANG]?.[k] ?? LANGS.es[k] ?? k}
function applyLanguage(lang){LANG=LANGS[lang]?lang:'es';localStorage.setItem(LANG_KEY,LANG);document.documentElement.lang=LANG;document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(LANGS[LANG][k]!=null)e.textContent=LANGS[LANG][k]});const sel=$('language');if(sel)sel.value=LANG;document.querySelectorAll('.help-btn').forEach(b=>b.title=t('help'));document.querySelectorAll('.help-close').forEach(b=>b.title=t('close'));const n=document.body.classList.contains('night');$('theme').textContent=n?t('dayMode'):t('darkMode');}
function initLanguage(){const sel=$('language');if(!sel)return;Object.entries(LANGS).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.name;sel.appendChild(o)});sel.onchange=()=>{applyLanguage(sel.value);render()};applyLanguage(localStorage.getItem(LANG_KEY)||'es')}
const HELP={
 es:{resultInput:'Introduce los resultados de la ruleta mediante los botones 0–36. El historial se utiliza como entrada para el análisis.',realtimePrediction:'Muestra la predicción actual generada por el conjunto de modelos a partir del historial disponible.',recentResults:'Muestra los últimos resultados registrados y permite elegir la tolerancia utilizada por el análisis.',recentJumps:'Muestra los saltos entre resultados consecutivos siguiendo el orden de la rueda europea.',recentDirections:'Indica la dirección del desplazamiento entre resultados consecutivos: CW, CCW o SAME.',predictionQuality:'Resume la calidad interna de la predicción combinando consenso, estabilidad, edge robusto, muestra y comportamiento reciente.',learningDiagnosis:'Muestra métricas del aprendizaje walk-forward y cómo han funcionado las familias de modelos con los datos disponibles.',adaptiveWeights:'Muestra el peso adaptativo asignado a cada familia según su rendimiento histórico y reciente.',activePatterns:'Lista los patrones repetidos que actualmente aportan evidencia al motor.',predictionHistory:'Muestra las predicciones históricas evaluadas frente al resultado real.',performanceTolerance:'Muestra el rendimiento de las predicciones dentro de la tolerancia seleccionada y lo compara con el baseline.'},
 en:{resultInput:'Enter roulette results using buttons 0–36. The history is used as input for the analysis.',realtimePrediction:'Shows the current prediction generated by the model ensemble from the available history.',recentResults:'Shows the latest recorded results and lets you choose the tolerance used by the analysis.',recentJumps:'Shows the jumps between consecutive results following the European wheel order.',recentDirections:'Shows the direction of movement between consecutive results: CW, CCW or SAME.',predictionQuality:'Summarizes internal prediction quality using consensus, stability, robust edge, sample size and recent behavior.',learningDiagnosis:'Shows walk-forward learning metrics and how the model families have performed on the available data.',adaptiveWeights:'Shows the adaptive weight assigned to each family based on historical and recent performance.',activePatterns:'Lists repeated patterns that currently provide evidence to the engine.',predictionHistory:'Shows historical predictions evaluated against the actual result.',performanceTolerance:'Shows prediction performance within the selected tolerance and compares it with the baseline.'},
 de:{resultInput:'Gib Roulette-Ergebnisse über die Tasten 0–36 ein. Der Verlauf dient als Eingabe für die Analyse.',realtimePrediction:'Zeigt die aktuelle Prognose des Modell-Ensembles auf Basis des verfügbaren Verlaufs.',recentResults:'Zeigt die zuletzt erfassten Ergebnisse und erlaubt die Auswahl der Analysetoleranz.',recentJumps:'Zeigt die Sprünge zwischen aufeinanderfolgenden Ergebnissen entlang des europäischen Rades.',recentDirections:'Zeigt die Bewegungsrichtung zwischen aufeinanderfolgenden Ergebnissen: CW, CCW oder SAME.',predictionQuality:'Fasst die interne Prognosequalität anhand von Konsens, Stabilität, robustem Edge, Stichprobe und aktuellem Verhalten zusammen.',learningDiagnosis:'Zeigt Walk-forward-Lernmetriken und die Leistung der Modellfamilien mit den verfügbaren Daten.',adaptiveWeights:'Zeigt die adaptiven Gewichte der einzelnen Familien basierend auf historischer und aktueller Leistung.',activePatterns:'Listet wiederholte Muster auf, die derzeit Evidenz für das Modell liefern.',predictionHistory:'Zeigt historische Prognosen im Vergleich zum tatsächlichen Ergebnis.',performanceTolerance:'Zeigt die Leistung innerhalb der gewählten Toleranz und vergleicht sie mit der Baseline.'},
 fr:{resultInput:'Saisissez les résultats de roulette avec les boutons 0–36. L’historique sert de base à l’analyse.',realtimePrediction:'Affiche la prédiction actuelle générée par l’ensemble de modèles à partir de l’historique disponible.',recentResults:'Affiche les derniers résultats enregistrés et permet de choisir la tolérance utilisée par l’analyse.',recentJumps:'Affiche les sauts entre résultats consécutifs selon l’ordre de la roue européenne.',recentDirections:'Affiche la direction entre résultats consécutifs : CW, CCW ou SAME.',predictionQuality:'Résume la qualité interne de la prédiction selon le consensus, la stabilité, l’edge robuste, l’échantillon et la récence.',learningDiagnosis:'Affiche les métriques d’apprentissage walk-forward et les performances des familles de modèles.',adaptiveWeights:'Affiche le poids adaptatif de chaque famille selon ses performances historiques et récentes.',activePatterns:'Liste les motifs répétés qui apportent actuellement des éléments au moteur.',predictionHistory:'Affiche les prédictions historiques comparées au résultat réel.',performanceTolerance:'Affiche les performances dans la tolérance choisie et les compare à la référence.'},
 it:{resultInput:'Inserisci i risultati della roulette con i pulsanti 0–36. La cronologia viene usata per l’analisi.',realtimePrediction:'Mostra la previsione corrente generata dall’insieme dei modelli usando la cronologia disponibile.',recentResults:'Mostra gli ultimi risultati registrati e consente di scegliere la tolleranza usata dall’analisi.',recentJumps:'Mostra i salti tra risultati consecutivi seguendo l’ordine della ruota europea.',recentDirections:'Mostra la direzione tra risultati consecutivi: CW, CCW o SAME.',predictionQuality:'Riassume la qualità interna della previsione usando consenso, stabilità, edge robusto, campione e recenza.',learningDiagnosis:'Mostra le metriche di apprendimento walk-forward e le prestazioni delle famiglie di modelli.',adaptiveWeights:'Mostra il peso adattivo di ogni famiglia in base alle prestazioni storiche e recenti.',activePatterns:'Elenca i pattern ripetuti che forniscono attualmente evidenza al motore.',predictionHistory:'Mostra le previsioni storiche confrontate con il risultato reale.',performanceTolerance:'Mostra le prestazioni entro la tolleranza scelta e le confronta con la baseline.'},
 pt:{resultInput:'Introduza os resultados da roleta usando os botões 0–36. O histórico é usado como entrada da análise.',realtimePrediction:'Mostra a previsão atual gerada pelo conjunto de modelos com base no histórico disponível.',recentResults:'Mostra os resultados mais recentes e permite escolher a tolerância usada na análise.',recentJumps:'Mostra os saltos entre resultados consecutivos seguindo a ordem da roleta europeia.',recentDirections:'Mostra a direção entre resultados consecutivos: CW, CCW ou SAME.',predictionQuality:'Resume a qualidade interna da previsão usando consenso, estabilidade, edge robusto, amostra e recência.',learningDiagnosis:'Mostra métricas de aprendizagem walk-forward e o desempenho das famílias de modelos.',adaptiveWeights:'Mostra o peso adaptativo de cada família com base no desempenho histórico e recente.',activePatterns:'Lista padrões repetidos que atualmente fornecem evidência ao motor.',predictionHistory:'Mostra previsões históricas comparadas com o resultado real.',performanceTolerance:'Mostra o desempenho dentro da tolerância escolhida e compara com o baseline.'},
 ru:{resultInput:'Вводите результаты рулетки кнопками 0–36. История используется как вход для анализа.',realtimePrediction:'Показывает текущий прогноз ансамбля моделей на основе доступной истории.',recentResults:'Показывает последние результаты и позволяет выбрать допуск анализа.',recentJumps:'Показывает переходы между последовательными результатами по порядку европейского колеса.',recentDirections:'Показывает направление между последовательными результатами: CW, CCW или SAME.',predictionQuality:'Суммирует внутреннее качество прогноза по консенсусу, стабильности, надёжному edge, выборке и актуальности.',learningDiagnosis:'Показывает метрики обучения walk-forward и результаты семейств моделей.',adaptiveWeights:'Показывает адаптивный вес каждого семейства на основе исторических и недавних результатов.',activePatterns:'Перечисляет повторяющиеся паттерны, которые сейчас дают данные модели.',predictionHistory:'Показывает исторические прогнозы в сравнении с фактическим результатом.',performanceTolerance:'Показывает результативность в выбранном допуске и сравнивает её с базовым уровнем.'},
 ja:{resultInput:'0～36のボタンでルーレット結果を入力します。履歴が分析の入力として使用されます。',realtimePrediction:'利用可能な履歴からモデルアンサンブルが生成した現在の予測を表示します。',recentResults:'最新の記録結果を表示し、分析に使用する許容差を選択できます。',recentJumps:'ヨーロピアンホイールの順序に沿った連続結果間のジャンプを表示します。',recentDirections:'連続結果間の方向を表示します：CW、CCW、SAME。',predictionQuality:'コンセンサス、安定性、ロバストEdge、サンプル、直近性から内部的な予測品質を要約します。',learningDiagnosis:'walk-forward学習の指標とモデルファミリーの実績を表示します。',adaptiveWeights:'過去および最近の実績に基づく各ファミリーの適応重みを表示します。',activePatterns:'現在エンジンに証拠を提供している反復パターンを一覧表示します。',predictionHistory:'過去の予測を実際の結果と比較して表示します。',performanceTolerance:'選択した許容差内での予測性能を表示し、ベースラインと比較します。'},
 zh:{resultInput:'使用0–36按钮输入轮盘结果。历史记录将作为分析输入。',realtimePrediction:'根据可用历史记录显示模型集成生成的当前预测。',recentResults:'显示最近记录的结果，并可选择分析使用的容差。',recentJumps:'按照欧洲轮盘顺序显示连续结果之间的跳跃。',recentDirections:'显示连续结果之间的方向：CW、CCW 或 SAME。',predictionQuality:'综合共识、稳定性、稳健Edge、样本和近期表现，总结内部预测质量。',learningDiagnosis:'显示walk-forward学习指标以及各模型族在现有数据上的表现。',adaptiveWeights:'根据历史和近期表现显示各模型族的自适应权重。',activePatterns:'列出当前为引擎提供证据的重复模式。',predictionHistory:'显示历史预测与实际结果的对比。',performanceTolerance:'显示所选容差内的预测表现，并与基线进行比较。'},
 ko:{resultInput:'0–36 버튼으로 룰렛 결과를 입력합니다. 기록은 분석의 입력으로 사용됩니다.',realtimePrediction:'사용 가능한 기록을 바탕으로 모델 앙상블이 생성한 현재 예측을 표시합니다.',recentResults:'최근 기록된 결과를 보여주며 분석에 사용할 허용오차를 선택할 수 있습니다.',recentJumps:'유럽식 휠 순서를 기준으로 연속 결과 사이의 점프를 보여줍니다.',recentDirections:'연속 결과 사이의 방향을 표시합니다: CW, CCW 또는 SAME.',predictionQuality:'합의, 안정성, 강건한 Edge, 표본 및 최근성을 사용해 내부 예측 품질을 요약합니다.',learningDiagnosis:'walk-forward 학습 지표와 사용 가능한 데이터에서 각 모델 계열의 성과를 표시합니다.',adaptiveWeights:'과거 및 최근 성과에 따른 각 모델 계열의 적응형 가중치를 표시합니다.',activePatterns:'현재 엔진에 근거를 제공하는 반복 패턴을 표시합니다.',predictionHistory:'과거 예측을 실제 결과와 비교해 보여줍니다.',performanceTolerance:'선택한 허용오차 내의 예측 성능을 표시하고 기준선과 비교합니다.'}
};
function openHelp(key){const m=$('helpModal');if(!m)return;$('helpTitle').textContent=t('help');$('helpText').textContent=HELP[LANG]?.[key]||HELP.es[key]||'';m.hidden=false}
function closeHelp(){const m=$('helpModal');if(m)m.hidden=true}
function initHelp(){document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>openHelp(b.dataset.help));document.querySelectorAll('[data-close-help]').forEach(b=>b.onclick=closeHelp);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeHelp()})}
initLanguage();initHelp();

$('theme').onclick=()=>{document.body.classList.toggle('night');const n=document.body.classList.contains('night');localStorage.setItem(THEME_KEY,n?'night':'day');$('theme').textContent=n?t('dayMode'):t('darkMode');drawChart()};
$('undo').onclick=undo;$('clear').onclick=clearAll;
$('tol').onchange=()=>{S.settings.tol=Number($('tol').value);invalidateAll();rebuildPredictions();save();render()};
$('chartWindow').value=String(S.settings.chartWindow);$('chartWindow').onchange=()=>{S.settings.chartWindow=Number($('chartWindow').value);save();drawChart()};
for(let n=0;n<=36;n++){const b=document.createElement('button');b.className='num '+col(n);b.textContent=n;b.onpointerdown=()=>{b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120)};b.onclick=()=>add(n);$('numbers').appendChild(b)}
if(localStorage.getItem(THEME_KEY)==='night'){document.body.classList.add('night');$('theme').textContent='Modo día'}
ensurePredictions();render();
})();
